### ISSUE TITLE
Veeam Managed Backup for VM above 2 TB size

### ISSUE THREAD

**Issue by snow-evy** [ovh/hosted-private-cloud-roadmap#77]
As a customer I would like to be able to use Veeam Backup-as-a-Service for VMs above 2 TB size, like databases, for example.

**Comment by franckcosta** [comment]
Hello,
We are working on the [new product for Veeam Manged Backup](https://github.com/ovh/hosted-private-cloud-roadmap/issues/87).
We are checking the possibility to raise the limit.

Please stay tune.
